#!/bin/sh

test -z "$1" && echo "Usage: $0 repo" && exit 1

echo "Start sync langs"

HOST=dev1.rz.kwick.de

cd ~/repos/$1 && (

rsync -avz --force -rtlq --bwlimit=256  --exclude '.idea' --exclude '.git' --exclude 'tmp' \
    $HOST:~/$1/langs/ ./langs
    
rsync -avz --force -rtlq --bwlimit=256  --exclude '.idea' --exclude '.git' --exclude 'tmp' \
    $HOST:~/$1/htdocs/img/js/langs/ ./htdocs/img/js/langs

)