#!/bin/sh

test -z "$1" && echo "Usage: $0 repo" && exit 1

echo "Sync langs up"

HOST=dev1.rz.kwick.de

cd ~/repos/$1 && (
    sudo chown -R $USER *
    chmod -R o+w *
    dev-sync $1
    ssh $HOST "cd ~/$1 && phing nuke"
)