#!/bin/sh

dir="jaumo.web"
echo "Start sync $dir down"

cd ~/repos/$dir && (

rsync -avz --force -rtlq --bwlimit=256  --exclude '.idea' --exclude '.git' --exclude 'tmp' \
    dev1.jaumo.com:~/$dir/ .
    

)