alias dev1="ssh dev1.dus7.jaumo.com"
alias k="kubectl"
alias s="ssh"
alias yipi="ssh yipi@yipi-store.com"
alias dc="docker-compose"
alias j="cd ~/repos/backend/backend"
alias JDEV="export JAUMO_ENV=Development"
alias JTEST="export JAUMO_ENV=Test"
alias JPROD="export JAUMO_ENV=Production"
alias JUTEST="export JAUMO_ENV=UnitTest"
alias pull="gsta && gprom && gstp"
ANDROID_HOME=/Users/br/Library/Android/sdk